# Use lightweight OpenJDK 21 base image
FROM eclipse-temurin:21-jdk-alpine
  
  # Set environment variables
ENV APP_HOME=/app
ENV JAVA_OPTS=""
  
  # Create application directory
WORKDIR $APP_HOME
  
  # Copy the built JAR into the container
COPY target/devices-api-*.jar app.jar
  
  # Expose the application port
EXPOSE 8080
  
  # Run the application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]